# Change to true for Disqus comments
disqus:
  comments: True
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Books', folder: 'pages', file: 'books.html'}
- {name: 'Deep Learning', folder: 'pages', file: 'dl.html'}
- {name: 'Reinforcement Learning', folder: 'pages', file: 'rl.html'}
- {name: 'Tech review', folder: 'pages', file: 'tech-review.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
#social:
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'envelope', link: 'mailto:stnoah1@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
#- {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Prev'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
